name: Feature Request
description: Propose a new feature for AgentMesh
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Is AgentMesh missing a feature that you'd like to see? Feel free to propose it here.

        Before you submit a feature:
        1. Search existing issues for similar features. If you find one, upvote it rather than opening a new one.
        2. Not all features will be accepted. We try to balance the varying needs of the community.

  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
